# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\HandSight\src\qt_designer_files\gestures_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gestures_widget(object):
    def setupUi(self, gestures_widget):
        gestures_widget.setObjectName("gestures_widget")
        gestures_widget.resize(900, 600)
        gestures_widget.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.gesture_list = QtWidgets.QListWidget(gestures_widget)
        self.gesture_list.setGeometry(QtCore.QRect(0, 0, 671, 600))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gesture_list.setFont(font)
        self.gesture_list.setObjectName("gesture_list")
        self.add_gesture_button = QtWidgets.QPushButton(gestures_widget)
        self.add_gesture_button.setGeometry(QtCore.QRect(710, 30, 159, 38))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_gesture_button.setFont(font)
        self.add_gesture_button.setStyleSheet("background-color: rgb(62, 65, 74);\n"
                                              "color: rgb(255, 255, 255);\n"
                                              "border-radius: 5px;")
        self.add_gesture_button.setObjectName("add_gesture_button")

        self.retranslateUi(gestures_widget)
        QtCore.QMetaObject.connectSlotsByName(gestures_widget)

    def retranslateUi(self, gestures_widget):
        _translate = QtCore.QCoreApplication.translate
        gestures_widget.setWindowTitle(_translate("gestures_widget", "Form"))
        self.add_gesture_button.setText(_translate("gestures_widget", "Добавить жест"))
