# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\HandSight\src\qt_designer_files\login_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_widget(object):
    def setupUi(self, login_widget):
        login_widget.setObjectName("login_widget")
        login_widget.resize(1280, 720)
        login_widget.setStyleSheet("background-color: rgba(217, 217, 217, 0.5);\n"
"")
        self.blur_widget = QtWidgets.QWidget(login_widget)
        self.blur_widget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.blur_widget.setStyleSheet("background-color: rgba(217, 217, 217, 0.5);")
        self.blur_widget.setObjectName("blur_widget")
        self.widget = QtWidgets.QWidget(login_widget)
        self.widget.setGeometry(QtCore.QRect(440, 120, 350, 450))
        self.widget.setStyleSheet("background-color: rgb(62, 65, 74);\n"
"border-color: rgb(217, 217, 217);\n"
"border-width: 3px;\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setGeometry(QtCore.QRect(60, 360, 230, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: rgb(217, 217, 217);")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.password_label = QtWidgets.QLabel(self.widget)
        self.password_label.setGeometry(QtCore.QRect(30, 180, 90, 27))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.password_label.setObjectName("password_label")
        self.login_label = QtWidgets.QLabel(self.widget)
        self.login_label.setGeometry(QtCore.QRect(30, 90, 48, 27))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.login_label.setObjectName("login_label")
        self.login_button = QtWidgets.QPushButton(self.widget)
        self.login_button.setGeometry(QtCore.QRect(80, 270, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("color: rgb(62, 65, 74);\n"
"background-color: rgb(217, 217, 217);\n"
"border-radius: 5px;")
        self.login_button.setObjectName("login_button")
        self.auth_label = QtWidgets.QLabel(self.widget)
        self.auth_label.setGeometry(QtCore.QRect(88, 40, 174, 39))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.auth_label.setFont(font)
        self.auth_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.auth_label.setObjectName("auth_label")
        self.login_line_edit = QtWidgets.QLineEdit(self.widget)
        self.login_line_edit.setGeometry(QtCore.QRect(30, 130, 290, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_line_edit.setFont(font)
        self.login_line_edit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 217, 217);\n"
"color: rgb(62, 65, 74);\n"
"border-radius: 5px;")
        self.login_line_edit.setObjectName("login_line_edit")
        self.register_button = QtWidgets.QPushButton(self.widget)
        self.register_button.setGeometry(QtCore.QRect(60, 320, 230, 25))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("color: rgb(62, 65, 74);\n"
"background-color: rgb(217, 217, 217);\n"
"border-radius: 5px;")
        self.register_button.setObjectName("register_button")
        self.password_line_edit = QtWidgets.QLineEdit(self.widget)
        self.password_line_edit.setGeometry(QtCore.QRect(30, 220, 290, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 217, 217);\n"
"color: rgb(62, 65, 74);\n"
"border-radius: 5px;")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")

        self.retranslateUi(login_widget)
        QtCore.QMetaObject.connectSlotsByName(login_widget)

    def retranslateUi(self, login_widget):
        _translate = QtCore.QCoreApplication.translate
        login_widget.setWindowTitle(_translate("login_widget", "Form"))
        self.error_label.setText(_translate("login_widget", "Приветствую в HandSight!"))
        self.password_label.setText(_translate("login_widget", "passowrd:"))
        self.login_label.setText(_translate("login_widget", "login:"))
        self.login_button.setText(_translate("login_widget", "Войти"))
        self.auth_label.setText(_translate("login_widget", "Авторизация"))
        self.login_line_edit.setPlaceholderText(_translate("login_widget", "Enter here"))
        self.register_button.setText(_translate("login_widget", "не зарегестрированы?"))
        self.password_line_edit.setPlaceholderText(_translate("login_widget", "Enter here"))
