# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\HandSight\src\qt_designer_files\video_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_video_widget(object):
    def setupUi(self, video_widget):
        video_widget.setObjectName("video_widget")
        video_widget.resize(900, 600)
        self.video_label = QtWidgets.QLabel(video_widget)
        self.video_label.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")

        self.retranslateUi(video_widget)
        QtCore.QMetaObject.connectSlotsByName(video_widget)

    def retranslateUi(self, video_widget):
        _translate = QtCore.QCoreApplication.translate
        video_widget.setWindowTitle(_translate("video_widget", "video"))
